version: "3.3"
services:
    webserver:
        build:
            context: .
        container_name: 'webtool38'
        restart: unless-stopped
        ports:
            - ${WWW_PORT}:80
        extra_hosts:
            - host.docker.internal:host-gateway
        volumes:
            - ${DOCUMENT_ROOT}:/var/www/html
            - ${PHP_INI-./docker/server/config/php/php.ini}:/usr/local/etc/php/php.ini
            - ${APACHE_VHOSTS_DIR-./docker/server/config/vhosts}:/etc/apache2/sites-enabled
            - ${APACHE_LOG_DIR-./docker/server/logs/apache2}:/var/log/apache2
        command: bash /var/www/html/install.sh
    node:
        image: node:21-alpine3.18
        container_name: 'webtool38_node'
        user: node
        working_dir: /web
        environment:
            - NODE_ENV=development
        volumes:
            - '.:/web'
        command: 'npm run dev -- --host=0.0.0.0 --port=${FORWARD_NODE_PORT}'
        ports:
            - ${FORWARD_NODE_PORT}:${FORWARD_NODE_PORT}
