<x-layout.child>
    <x-slot:left>
        <div
            hx-trigger="load"
            hx-target="this"
            hx-swap="outerHTML"
            hx-get="/relationgroup/{{$data->idRelationGroup}}/rts/formNew"
        ></div>
    </x-slot:left>
    <x-slot:right>
        <div
            hx-trigger="load"
            hx-target="this"
            hx-swap="outerHTML"
            hx-get="/relationgroup/{{$data->idRelationGroup}}/rts/grid"
        ></div>
    </x-slot:right>
</x-layout.child>

